spring:
  datasource:
    url: jdbc:mysql://121.37.174.33:3306/soul_roomie?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: roomiesoul2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 30
    hikari:
      readOnly: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 300000
      loginTimeout: 5

      max-lifetime: 300000
      connection-test-query: SELECT 1
      minimum-idle: 3
      maximum-pool-size: 20
server:
  port: 8082
mybatis:
  type-aliases-package: com.soulroomie.demo.comsumer.service.model
  config-location: classpath:mybatis-config.xml
  auto-mapping-behavior: partial
  map-underscore-to-camel-case: true
